version: "3"
services:
  pay-9001:
    image: pay_9001:01
    restart: on-failure
    ports:
      - 9001:9001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 10M
  order-83:
    image: order_83:01
    restart: on-failure
    ports:
      - 83:83
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 10M